import numpy as np
import pandas as pd
# For visualizations
import matplotlib.pyplot as plt
# For regular expressions
import re
# For handling string
import string
# For performing mathematical operations
import math
from sklearn.feature_extraction.text import TfidfVectorizer

no_of_lines = 0

jd_kw_file = r"C:\Users\krkc6\Desktop\Analyst_test"
appendFile = open(jd_kw_file, 'r', encoding='utf-8')
lines = appendFile.readlines()
for line in lines:
    no_of_lines = no_of_lines + 1

document1 = 'Apply now Castles Solicitors are looking for a part / full time Legal Secretary / Admin Assistant to join their team in Hurstpierpoint, working across multiple departments (flexible working hours available ideally 20+ hours a week) Essential skills: Microsoft and excel competentAbility to communicate with clients via email and telephoneOrganisation / good time managementAbility to work independently and as part of a teamGCSE Maths and English C or above Desirable but not essential as full training will be given: Legal background / qualificationsPrevious office experienceExperience with case management systems Role: Communicating with clients and creating appointments / general diary managementOpening and closing fileGeneral correspondence with clients and third partiesDrafting legal documentsTyping from dictationGeneral admin roles'
document2 = "Apply on employer's website Retail Advisor - Belfast Donnegal Place - 20hours/week Â£9,100 pa rising to Â£9,152 pa after probation (OTE Â£10,592) Are you Ready? Are you poised for a challenge? Could you make the difference for our customers? If you answered yes to the above - we want to hear from you! Now is a great time to join us, here is a snippet of our recent awards: Best High Street Retailer 2017 (Mobile Industry awards) Best for Innovation 2017 (Mobile Industry awards) Best Telecoms & Technology Campaign (Performance Marketing Awards) The Times Top 50 Employers for Women in 2017 There are many more to come with your helpâ€¦ Our question to you â€“ do you want to be part of this family of success seekers? Want to deliver the best service to our customers at the heart of our business? We want people who want to be the best, to join our Retail team. Do you have the drive and ambition to work to a number of team and individual targets? Are you resilient and looking for a supportive company to push you and your career in the only direction we know â€“ UP! If you are successful in joining our award winning team, we will train you for the first 12 weeks of employment where we will pay you Â£8.75 rising to Â£8.80. Youâ€™ll also have the opportunity to earn on top of this as you deliver results against your targets. Whatâ€™s not to love? Start your journey with us by clicking apply and we will be on hand to help you along the way. We look forward to speaking with you soon! Vodafone is committed to attracting, developing and retaining the very best people by offering a flexible, motivating and inclusive workplace in which talent is truly recognised, developed and rewarded. We believe that diversity plays an important role in the success of our business and we are committed to creating an inclusive work environment which respects, values, celebrates and makes the most of peopleâ€™s individual differences - we are not only multinational but multicultural too. Please let us know if you require any alterations or adjustments to support you through your recruitment journey. Please note that all candidates internal and external will be subject to baseline security checks and Vodafone reserves the right to terminate employees that do not meet our minimum vetting requirements. Want to refer a Friend? Please click the link below and follow a few easy steps:https://market/uk/hr/Pages/Employee-Referral-Scheme.aspx"
document3 = " Apply aspire cambridge currently seeking Analyst join client based Newmarket, Suffolk. This role involves processing samples data accordance clients Quality Management Systems, maintaining analytical instrumentation equipment, entering accurate timely results onto Company LIMS system conducting sample preparation required. The successful candidate degree level qualified relevant subject, proven analytical experience. Start: ASAP Location: Newmarket, Suffolk Hours: M-F Full Time Salary: Â£18,800 Â£22,540 If interested position, feel relevant skills would like apply please call team apply online. Whilst we'd love get back every applicant, always possible, heard us within 3-5 days, please note application successful occasion. aspire cambridge ltd acting employment agency regards vacancy. Our accredited recruitment consultants offer specialist marketplace expertise across seven specialist recruitment divisions; engineering manufacturing, finance accountancy, hospitality, information technology, legal hr, office support sales marketing. Our ever-expanding network client companies exceeds 3000 active organisations engage regular basis. We unrivaled knowledge jobs marketplace wonder hold impressive track record exceeding client candidate expectations. How it? By placing people first"
document4 = "Apply Analyst, permanent job, analyst job, Coventry Your new company A global leading logistics business excellent development career progression opportunities. This large organisation offices based across UK Europe. Your new role Based Coventry office, joining large team 27, joining team Analyst We looking candidate able support department service level (EDW) & compensation related data analysis, maintenance development organisations report systems & structures. You also 'technical lead' within department. Roles responsibilities include: Analysis evaluation: Performs financial statistical analysis related assigned Strategic Account projects/processes. Presents analysis recommendations appropriate formats aid understanding. Monitors evaluates cost/performance assigned areas recommends actions needed achieve goals ad hoc basisOperations research: Develops analytical models tools use simulation, maximisation development business models; develops prototypes test alternatives solutions; analyses using modelling operations research techniques order maximise efficiency accuracy analysis.Quality Assurance compliance: Supports quality assurance processes developing recommending specific audit criteria, methods tools evaluate report required elements Strategic Account projects/process compliance. Uses established methods/tools evaluate assigned processes determines compliance gaps proposes solutions order improve service cost performance within responsible area.Project Management: Monitors plans assigned projects. Develops recommends enhancements manage report project progress/results assists post-implementation review measure success service improvements.Process Mapping: Creates detailed mapping new existing processes; may include alternatives consideration. Presents Manager/Project Lead participates review evaluation. Maintains assigned processes. What need succeed In order considered role, need following: Previous experience analytical role.Ability analyse large quantities data variety sources able present back recommendations.Excellent IT systems knowledge including advanced level ExcelA working knowledge coding. What get return A competitive annual salary Â£30K - Â£33K dependent upon experience + annualised bonus based company performance. Excellent development career opportunities. What need nowIf interested role, click 'apply now' forward up-to-date copy CV, call us now.If job quite right looking new position, please contact us confidential discussion career. Hays Specialist Recruitment Limited acts employment agency permanent recruitment employment business supply temporary workers. By applying job accept T&C's, Privacy Policy Disclaimers found hays.co.uk"

vectorizer = TfidfVectorizer()
vectors = vectorizer.fit_transform([document1, document2, document3, document4])
feature_names = vectorizer.get_feature_names()
dense = vectors.todense()
denselist = dense.tolist()
df = pd.DataFrame(denselist, columns=feature_names)

print(df)

